import Head from 'next/head'
import dynamic from "next/dynamic";
import styles from '../styles/Home.module.css'
import BurnPage from '../components/BurnPage'

import { FC } from 'react';

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BurnPage></BurnPage>
      </main>
    </>
  )
}

export default dynamic(() => Promise.resolve(Home), { ssr: false });
