import Head from 'next/head'
import Image from 'next/image'
import dynamic from "next/dynamic";
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import BurnPage from '../components/BurnPage'

const inter = Inter({ subsets: ['latin'] })

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <BurnPage></BurnPage>
      </main>
    </>
  )
}

export default dynamic(() => Promise.resolve(Home), { ssr: false });
